language: python
python:
  - "3.6"
  - "nightly"

env:
  - DJANGO_VERSION=Django==2.0.5

addons:
  postgresql: "10"


before_script:
  - psql -U postgres -c "create extension postgis"

install: 
  - "pip install -r requirements.txt"
  - "pip install -q $DJANGO_VERSION"

script: "python manage.py test"
