# Generated by Django 2.0.5 on 2018-05-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='sizex',
            new_name='cols',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='sizey',
            new_name='rows',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='col',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='row',
            new_name='y',
        ),
    ]
