# Generated by Django 2.0.5 on 2018-05-15 11:37
from django.contrib.postgres.operations import CreateExtension
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_auto_20180511_1631'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.RemoveField(
            model_name='farm',
            name='height',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='width',
        ),
        migrations.AddField(
            model_name='farm',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
